version: "3.8"
services:
  # service:
  #   build:
  #     context: ./service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "20010:80"
  #   volumes:
  #     - ./service/:/app/service/
  web:
    image: nginx:latest
    ports:
      - "20000:80"
    volumes:
      - ./web/:/usr/share/nginx/html/
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/:/var/www/html/
    networks:
      - microservices
      - default
  php:
    image: php:7.4-fpm
    volumes:
      - ./web/:/var/www/html/
  gate:
    build:
      context: ./gate
      dockerfile: Dockerfile
    ports:
      - "20010:80"
    volumes:
      - ./gate/:/app/
    networks:
      - microservices
      - default
  print:
    build:
      context: ./print
      dockerfile: Dockerfile
    ports:
      - "20020:80"
    volumes:
      - ./print/:/app/
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  default:
  microservices:
    driver: bridge
    external: false